nodeLinker: node-modules

packageExtensions:
  eslint-config-airbnb-typescript@*:
    peerDependencies:
      eslint: ^5.16.0 || ^6.8.0 || ^7.2.0
      eslint-plugin-import: ^2.21.2
      eslint-plugin-jsx-a11y: ^6.3.0
      eslint-plugin-react: ^7.20.0
      eslint-plugin-react-hooks: ^4 || ^3 || ^2.3.0 || ^1.7.0

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"

yarnPath: .yarn/releases/yarn-3.0.2.cjs
